
from agrotech import db,app,login_manager
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return Login.query.get(int(user_id))


class Login(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(50),unique=True)
    password = db.Column(db.String(200))
    usertype = db.Column(db.String(20))


class Contact(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    email = db.Column(db.String(202))
    phone = db.Column(db.String(202))
    message = db.Column(db.String(220))

class Far_feedback(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    email = db.Column(db.String(202))
    phone = db.Column(db.String(202))
    message = db.Column(db.String(220))


class Regstaff(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    fname = db.Column(db.String(250))
    sname = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    district = db.Column(db.String(250))
    position = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    password = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Cart(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    bcode = db.Column(db.String(250))
    bname = db.Column(db.String(250))
    author =db.Column(db.String(250))
    publication = db.Column(db.String(250))
    pub_year = db.Column(db.String(250))
    price = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Addtraining(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    programer =db.Column(db.String(250))
    contact = db.Column(db.String(250))
    date = db.Column(db.String(250))
    time = db.Column(db.String(250))
    topic = db.Column(db.String(250))

class Magazine(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    author =db.Column(db.String(250))
    publisher =db.Column(db.String(250))
    features = db.Column(db.String(250))
    rupees = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Addsoiltest(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    contact = db.Column(db.String(250))
    day = db.Column(db.String(250))
    time = db.Column(db.String(250))



class Shmreg(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    cropname = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Soilbooknow(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    aadhar = db.Column(db.String(250))
    approve = db.Column(db.String(250))
    status = db.Column(db.String(202))

class Machinebooknow(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    aadhar = db.Column(db.String(250))
    approve = db.Column(db.String(250))
    status = db.Column(db.String(202))

   
class Trainingbooking(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    aadhar = db.Column(db.String(250))
    approve = db.Column(db.String(250))
    status = db.Column(db.String(202))


class Farmerreg(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class An_farmerreg(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Machines(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    machines = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Fertiliz(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    category = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Cowdairy(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    cowsnum = db.Column(db.String(250))
    ctype = db.Column(db.String(250))
    category = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Goatfarm(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    goatnum = db.Column(db.String(250))
    gtype = db.Column(db.String(250))
    category = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Hfarm(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    num = db.Column(db.String(250))
    htype = db.Column(db.String(250))
    category = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Insurcrop(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    cropname = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Calamity(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    cropname = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Soil_health(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    cropname = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Pmkisan(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class An_pmk(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Livestock(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    animaltype = db.Column(db.String(250))
    animalnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Electricity(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    connid = db.Column(db.String(250))
    spented = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Polyhouse(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    spented = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Pension(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Pension_an(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    farmerid = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Pm_fasal(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class One_crore(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    cropname = db.Column(db.String(250))
    cropnum = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')    

class Bamboo_reg(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')    


class Addfeed(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    fname = db.Column(db.String(250))
    lname = db.Column(db.String(250))
    email = db.Column(db.String(202),unique=True)
    phone = db.Column(db.String(202))
    message = db.Column(db.String(220))

class Regfarmer(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address = db.Column(db.String(250))
    gender = db.Column(db.String(250))
    email = db.Column(db.String(202),unique=True)
    phone = db.Column(db.String(202))
    password = db.Column(db.String(202))
    status = db.Column(db.String(202))

class Animalfarmer(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address = db.Column(db.String(250))
    gender = db.Column(db.String(250))
    email = db.Column(db.String(202),unique=True)
    phone = db.Column(db.String(202))
    password = db.Column(db.String(202))
    status = db.Column(db.String(202))
    
class Addprod(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    productname = db.Column(db.String(250))
    productcat = db.Column(db.String(250))
    features = db.Column(db.String(400))
    price = db.Column(db.String(250))
    contactnum = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Machine_rent(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    productname = db.Column(db.String(250))
    brant = db.Column(db.String(250))
    rentrupee = db.Column(db.String(250))
    features = db.Column(db.String(400))
    contactnum = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Addevent(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    eventname = db.Column(db.String(250))
    description = db.Column(db.String(250))
    date = db.Column(db.String(250))
    time = db.Column(db.String(400))
    place = db.Column(db.String(250))
    contactnum = db.Column(db.String(250))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')


class Addnotice(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    subject = db.Column(db.String(250))
    topic = db.Column(db.String(250))
    details = db.Column(db.String(250))
    date = db.Column(db.String(250))
    contactnum = db.Column(db.String(400))
    email = db.Column(db.String(250),unique=True)
    


class Loanform(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    projtopic = db.Column(db.String(250))
    projdisc = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')

class Loananimal(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(250))
    address =db.Column(db.String(250))
    gender = db.Column(db.String(250))
    dob = db.Column(db.String(250))
    phone = db.Column(db.String(250))
    email = db.Column(db.String(250),unique=True)
    block = db.Column(db.String(250))
    panchayath = db.Column(db.String(250))
    village = db.Column(db.String(250))
    bank = db.Column(db.String(250))
    accountnum = db.Column(db.String(250))
    aadharnum = db.Column(db.String(250))
    rationnum = db.Column(db.String(250))
    area = db.Column(db.String(250))
    projtopic = db.Column(db.String(250))
    projdisc = db.Column(db.String(250))
    verify = db.Column(db.String(250))
    status = db.Column(db.String(202))
    img = db.Column(db.String(20), nullable=False, default='default.jpg')
